# Generated by Django 2.2.13 on 2020-06-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='causes',
            field=models.ManyToManyField(blank=True, related_name='supporters', to='supporters.Cause'),
        ),
    ]
